version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit_message:
      prefix: "chore"
      include_scope: true

  - package-ecosystem: pip
    directory: "backend/"
    schedule:
      interval: weekly
    commit_message:
      prefix: "chore"
      include_scope: true

  - package-ecosystem: npm
    directory: "frontend/"
    schedule:
      interval: weekly
    commit_message:
      prefix: "chore"
      include_scope: true

  - package-ecosystem: npm
    directory: "infra/"
    schedule:
      interval: daily
    commit_message:
      prefix: "chore"
      include_scope: true

  # - package-ecosystem: docker
  #   directory: "/"
  #   schedule:
  #     interval: daily
