repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: pretty-format-json
        exclude: ^.vscode/|frontend/tsconfig.json  # is invalid json, but expected
      - id: check-json
        exclude: ^.vscode/|frontend/tsconfig.json  # is invalid json, but expected
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
    - id: bandit
      args: ["-c", "backend/pyproject.toml"]
      additional_dependencies: ["bandit[toml]"]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.10.0'
      hooks:
      -   id: mypy
          additional_dependencies:
            - "pydantic"
            - "types-requests"
            - "types-python-slugify"
