// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zChangePassword = z.object({
  old_password: z.string(),
  new_password: z.string(),
});

export const zConfirmForgotPassword = z.object({
  email: z.string(),
  confirmation_code: z.string(),
  new_password: z.string(),
});

export const zConfirmSignUp = z.object({
  email: z.string(),
  confirmation_code: z.string(),
});

export const zCurrentUser = z.object({
  id: z.string(),
  username: z.string(),
  email: z.string(),
  email_is_verified: z.union([z.boolean(), z.null()]).optional(),
  groups: z.array(z.string()).optional().default([]),
  picture: z.union([z.string(), z.null()]).optional(),
  first_name: z.union([z.string(), z.null()]).optional(),
  last_name: z.union([z.string(), z.null()]).optional(),
  phone_number: z.union([z.string(), z.null()]).optional(),
  phone_number_is_verified: z.union([z.boolean(), z.null()]).optional(),
});

export const zDetail = z.object({
  loc: z.union([z.array(z.unknown()), z.enum(['general'])]),
  msg: z.string(),
  code: z.string(),
});

export const zErrorLocation = z.enum(['body', 'query', 'header', 'cookies', 'params']);

export const zErrorLocationField = z.enum(['general']);

export const zForgotPassword = z.object({
  email: z.string(),
});

export const zHttpValidationError = z.object({
  detail: z
    .array(
      z.object({
        loc: z.array(z.unknown()),
        msg: z.string(),
        type: z.string(),
      }),
    )
    .optional(),
});

export const zHealth = z.object({
  status: z.enum(['OK', 'ERROR']).optional(),
  timestamp: z.string(),
});

export const zOAuthUrl = z.object({
  url: z.string(),
});

export const zPlan = z.object({
  id: z.string(),
  name: z.string(),
  description: z.union([z.string(), z.null()]).optional(),
});

export const zPlans = z.object({
  items: z.array(zPlan),
});

export const zResendConfirmationCode = z.object({
  email: z.string(),
});

export const zResponseFormat = z.object({
  code: z.string(),
  msg: z.string(),
});

export const zSignIn = z.object({
  username: z.string(),
  password: z.string(),
});

export const zSignUp = z.object({
  email: z.string(),
  password: z.string(),
});

export const zValidationError = z.object({
  loc: z.array(z.unknown()),
  msg: z.string(),
  type: z.string(),
});

export const zAuthGetSignInGoogleResponse = zOAuthUrl;

export const zAuthPostSignUpResponse = zResponseFormat;

export const zAuthPostConfirmSignUpResponse = zResponseFormat;

export const zAuthPostResendConfirmationCodeResponse = zResponseFormat;

export const zAuthPostForgotPasswordResponse = zResponseFormat;

export const zAuthPostConfirmForgotPasswordResponse = zResponseFormat;

export const zAuthPostChangePasswordResponse = zResponseFormat;

export const zAuthGetMeResponse = z.union([zCurrentUser, zDetail]);

export const zHealthGetHealthResponse = zHealth;

export const zPolarWebhookPaymentsWebhookPostResponse = z.object({});

export const zPaymentsGetPlansResponse = zPlans;

export const zPaymentsGetPlansRefreshResponse = zPlans;

export const zPaymentsGetPlanResponse = zPlan;
