# https://github.com/marketplace/actions/pre-commit-autoupdate/
# We are doing this because dependabot does not support pre-commit autoupdate.
name: Pre-commit auto-update

on:
  # every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # on demand
  workflow_dispatch:

# Add permissions to create pull requests
permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      # This update will run the pre-commit. To make it work it needs the frontend/eslint
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install --production=false
          dir: frontend

      - uses: browniebroke/pre-commit-autoupdate-action@v1.0.0

      - uses: peter-evans/create-pull-request@v7
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: "chore: update pre-commit hooks"
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
